version: 2.1
orbs:
  mac: circleci/macos@2.5.2

jobs:
  build_and_test:
    macos:
      xcode: 14.2.0
    environment:
      MAC_ORB_VNC_PASSWORD: "12345"
    steps:
      - checkout
      - mac/enable-vnc
      - run:
          name: Run tests
          command: sleep 32400
      - persist_to_workspace:
          root: .
          paths:
            - '*'

workflows:
  test_my_app:
    jobs:
      - build_and_test
