version: 2.1
orbs:
  mac: circleci/macos@2.3.0

jobs:
  build_and_test:
    macos:
      xcode: 14.2.0 # Specify your required Xcode version
    steps:
      - checkout
      - mac/enable-vnc
      - run:
          name: Run tests
          command: sleep 9h
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  deploy:
    macos:
      xcode: 14.2.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy step
          command: echo "Deploying..."

workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: main
