version: 2.1
orbs:
  mac: circleci/macos@2.3.0

jobs:
  build_and_test:
    macos:
      xcode: 14.2.0
    environment:
      MAC_ORB_VNC_PASSWORD: "12345"
    steps:
      - checkout
      - run:
          name: Enable Screen Sharing & VNC (attempt)
          command: |
            sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
              -activate -configure -access -on -users "$USER" -privs -all -restart -agent
            sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
              -configure -clientopts -setvnclegacy -vnclegacy yes
            sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
              -configure -clientopts -setmenuextra -menuextra yes
            sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
              -configure -clientopts -setremotecontrol -remotecontrol yes
            sudo dscl . -create /Users/vncuser
            sudo dscl . -create /Users/vncuser UserShell /bin/bash
            sudo dscl . -create /Users/vncuser RealName "VNC User"
            sudo dscl . -create /Users/vncuser UniqueID 1010
            sudo dscl . -create /Users/vncuser PrimaryGroupID 20
            sudo dscl . -create /Users/vncuser NFSHomeDirectory /Users/vncuser
            sudo dscl . -passwd /Users/vncuser 12345
            sudo dscl . -append /Groups/admin GroupMembership vncuser
            sudo createhomedir -c -u vncuser
      - run:
          name: Run tests
          command: sleep 32400
      - persist_to_workspace:
          root: .
          paths:
            - '*'

workflows:
  test_my_app:
    jobs:
      - build_and_test
